[package]
name = "nickel-helloworld"
version = "0.1.0"
authors = ["shinriyo"]

[dependencies]
nickel = "*"
#postgres = "*"
postgres = "0.11"
openssl = "*"
rustc-serialize = "0.3"

[dependencies.nickel_postgres]
git = "https://github.com/nickel-org/nickel-postgres.git"
