[package]
name = "nickel-helloworld"
version = "0.1.0"
authors = ["shinriyo"]

[dependencies]
nickel = "*"
postgres = "0.11" # https://github.com/sfackler/rust-postgres/
openssl = "*"
rustc-serialize = "*"
hyper = "*"
