[package]
name = "nickel-helloworld"
version = "0.1.0"
authors = ["shinriyo"]

[dependencies]
nickel = "*"
# https://github.com/sfackler/rust-postgres/
postgres = "0.11"
openssl = "*"
rustc-serialize = "0.3"
